#+TITLE: A Literate GNU Emacs Configuration
#+PROPERTY: header-args :tangle yes

* Setting Up The Repositories

This section populates the ~package-archives~ list with the desired Emacs package repositories. The elements of this list are /name-URL/ pairs.

#+BEGIN_SRC emacs-lisp
  (require 'package)
  (package-initialize)
  (setq package-install-upgrade-built-in t)
  (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/"))
  (add-to-list 'package-archives '("nongnu" . "https://elpa.nongnu.org/nongnu/"))
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
  (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/"))
#+END_SRC

* Configuring ~use-package~

[[https://github.com/jwiegley/use-package][use-package]] provides macros for loading and configuring Emacs packages. We'll load it here, installing it from the repositories if it's not already installed.

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package)
	  (package-refresh-contents)
	  (package-install 'use-package))

  (eval-when-compile
    (require 'use-package))
#+END_SRC

* Configuring Emacs

Here, I put my base Emacs configurations into a single ~use-package~ block to keep everything in one place, and to shorten some common expressions using the ~:hook~ and ~:custom~ options.

#+BEGIN_SRC emacs-lisp
  (use-package emacs
    :config
    ;; Disable the tool bar (graphical only)
    (tool-bar-mode 0)
    ;; Enable menu bar in graphical mode
    (menu-bar-mode (if (display-graphic-p) 1 0))
    ;; Use light them in graphical mode and dark theme otherwise
    (load-theme (if (display-graphic-p) 'modus-operandi 'modus-vivendi))
    ;; Enable column numbering
    (column-number-mode)
    ;; Disable scroll bars
    (scroll-bar-mode 0)
    ;; Use minimal fringes
    (fringe-mode '(1 . 1))
    ;; Enable performance mitigations for files with long lines
    (global-so-long-mode)
    :hook
    ;; Enable line numbering in `prog-mode'
    (prog-mode . display-line-numbers-mode)
    :custom
    ;; Set garbage collector threshold to 3M
    (gc-cons-threshold 3000000)
    ;; Set relative line numbering
    (display-line-numbers-type 'relative)
    ;; Don't display the startup message
    (inhibit-startup-message t)
    ;; Make prompt in `comint-mode' readonly
    (comint-prompt-read-only t)
    ;; Disable the bell
    (ring-bell-function #'ignore))
#+END_SRC

* Populating the Executable Path

When Emacs is run as a graphical application in MacOS, or as a daemon, it inherits a minimal set of environment variables from the system. If the user sets environment variables in their shell configuration, these won't be picked up by Emacs, causing some processes to behave unexpectedly.

This package remedies this issue by forcing Emacs to inherit environment variables from the user's shell at runtime.

#+BEGIN_SRC emacs-lisp
  (use-package exec-path-from-shell
    :functions exec-path-from-shell-initialize
    :custom (exec-path-from-shell-arguments nil)
    :config
    (when (or (memq window-system '(mac ns x))
	      (daemonp)) (exec-path-from-shell-initialize)))
#+END_SRC

* Using VIM Bindings

#+BEGIN_SRC emacs-lisp
  (setq scroll-step 1
	scroll-conservatively 10000
	next-screen-context-lines 5
	line-move-visual nil)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package evil
    :functions evil-mode
    :config
    (setq-default evil-undo-system 'undo-redo)
    (evil-mode 1))
#+END_SRC

** VIM Surround

The [[https://github.com/emacs-evil/evil-surround][evil-surround]] package provides the same functionality as tpope's VIM plugin, [[https://github.com/tpope/vim-surround][vim-surround]].

#+BEGIN_SRC emacs-lisp
  (use-package evil-surround
    :requires evil
    :functions global-evil-surround-mode
    :config
    (global-evil-surround-mode 1))
#+END_SRC

#+ATTR_LATEX: :environment tabularx :width \textwidth :align XX
| Mapping                       | Description                                                                                               |
|-------------------------------+-----------------------------------------------------------------------------------------------------------|
| ~ds<target>~                  | Deletes the target.                                                                                       |
| ~cs<target><replacement>~     | Replaces the target with the given replacement.                                                           |
| ~ys<textobject><replacement>~ | Surrounds the text object with the given replacement.                                                     |
| ~yss<replacement>~            | Surrounds the whole line with the given replacement, ignoring leading whitespace.                         |
| ~yS<textobject><replacement>~ | Surrounds the text object with the given replacement, indenting the content and placing it on a new line. |
| ~ySS<replacement>~            | Surrounds the whole line with the given replacement, indenting the content and placing it on a new line.  |
| ~S<replacement>~              | In visual mode, surround the selection with the given replacement.                                        |
| ~gS<replacement>~             | In visual mode, surround the selection with the given replacement, suppressing automatic indentation.     |

| Mapping          | Target                                  |
|------------------+-----------------------------------------|
| ~(~, ~)~, or ~b~ | Parentheses, i.e. ~(~ and ~)~           |
| ~{~, ~}~, or ~B~ | Braces, i.e. ~{~ and ~}~                |
| ~[~, ~]~, or ~r~ | Brackets, i.e. ~[~ and ~]~              |
| ~>~ or ~a~       | Angle brackets, i.e. ~<~ and ~>~        |
| ~<~  or ~t~      | HTML or XML tags, e.g. ~<p>~ and ~</p>~ |

| Mapping              | Replacement                                              |
|----------------------+----------------------------------------------------------|
| ~)~ or ~b~           | Parentheses, e.g. ~(foo)~                                |
| ~(~                  | Parentheses with inner space, e.g. ~( foo )~             |
| ~}~ or ~B~           | Braces, e.g. ~{foo}~                                     |
| ~{~                  | Braces with inner space, e.g. ~{ foo }~                  |
| ~]~ or ~r~           | Brackets, e.g. ~[foo]~                                   |
| ~[~                  | Brackets with inner space, e.g. ~[ foo ]~                |
| ~>~ or ~a~           | Angle brackets, e.g. ~<foo>~                             |
| ~<~ or ~t~           | An HTML or XML tag. Prompts for tag attributes.          |
| ~f~                  | A function. Prompts for function name, e.g. ~print(foo)~ |

* Document Conversion with Pandoc

Pandoc allows us to convert our working file into one of many document formats. The [[https://joostkremers.github.io/pandoc-mode/][pandoc-mode]] plugin integrates this tool in the editor with an interactive menu. Here, I have the mode enabled when working in Markdown or TeX mode.

#+BEGIN_SRC emacs-lisp
  (use-package pandoc-mode
    :hook
    (markdown-mode . pandoc-mode)
    (tex-mode . pandoc-mode))
#+END_SRC

* Magit

#+BEGIN_SRC emacs-lisp
  (use-package magit)
#+END_SRC

* Using the System Clipboard

When running Emacs in the terminal, yanked text is copied to an internal buffer. The ~xclip~ package allows Emacs to copy and paste from the system clipboard using external command line tools.

#+BEGIN_SRC emacs-lisp
  (use-package xclip
    :functions xclip-mode
    :config
    (xclip-mode 1))
#+END_SRC

* EditorConfig Support

The EditorConfig package looks for ~.editorconfig~ files in the project directory and configures editor settings based on the directives within the file. See the [[https://editorconfig.org/][EditorConfig documentation]] for more information.

#+BEGIN_SRC emacs-lisp
  (use-package editorconfig
    :functions editorconfig-mode
    :config
    (editorconfig-mode 1))
#+END_SRC

#+ATTR_LATEX: :environment tabularx :width \textwidth :align XX
| EditorConfig Properties    | Description                                                                                 |
|----------------------------+---------------------------------------------------------------------------------------------|
| ~indent_style~             | Indent with tabs or spaces.                                                                 |
| ~indent_size~              | The number of columns used for each indentation level, as well as the width of soft tabs.   |
| ~tab_width~                | The number of columns used to represent a tab character.                                    |
| ~end_of_line~              | Determines how line breaks are represented.                                                 |
| ~charset~                  | Determines the character set.                                                               |
| ~trim_trailing_whitespace~ | Whether or not to remove any whitespace characters preceding newline characters.            |
| ~insert_final_newline~     | Whether or not to ensure file ends with a newline when saving.                              |
| ~max_line_length~          | Force hard wrapping at the given number of characters, or don't force hard wrapping at all. |
| ~root~                     | Whether or not to stop the ~.editorconfig~ file search on the current file.                 |

* Customizing the Minibuffer

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :defines which-key-idle-delay
    :functions which-key-mode
    :config
    (setq which-key-idle-delay 0.5)
    (which-key-mode 1))
#+END_SRC

[[https://github.com/minad/vertico][Vertico]] displays minibuffer completions in a vertical interactive menu.

#+BEGIN_SRC emacs-lisp
  (use-package vertico
    :functions vertico-mode
    :config
    (vertico-mode))
#+END_SRC

[[https://github.com/minad/marginalia][Marginalia]] adds annotations to items in the minibuffer completions.

#+BEGIN_SRC emacs-lisp
  ;; Enable rich annotations using the Marginalia package
  (use-package marginalia
    ;; Bind `marginalia-cycle' locally in the minibuffer. To make the binding
    ;; available in the *Completions* buffer, add it to the
    ;; `completion-list-mode-map'.
    :bind (:map minibuffer-local-map
	   ("M-A" . marginalia-cycle))
    ;; The :init section is always executed.
    :init
    ;; Marginalia must be activated in the :init section of use-package
    ;; such that the mode gets enabled right away. Note that this forces
    ;; loading the package.
    (marginalia-mode))
#+END_SRC

* Language Support

** Haskell

Here ~haskell-interactive-popup-errors~ is set to ~nil~ to prevent errors from being shown in a seperate buffer. Instead errors are shown in the minibuffer, or in the interactive Haskell buffer if one exists.

#+BEGIN_SRC emacs-lisp
  (use-package haskell-mode
    :custom (haskell-interactive-popup-errors nil)
    :mode ("\\.hs\\'" . haskell-mode))
#+END_SRC

** Markdown

[[https://jblevins.org/projects/markdown-mode/][Markdown Mode]] adds editor support for Markdown. Setting ~markdown-asymmetic-header~ to ~t~ allows for ~# Header~ style headers to be used in addition to ~# Header #~ style headers and setting ~markdown-enable-math~ to ~t~ enables support for LaTeX math expressions.

#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :mode "\\.\\(md\\|markdown\\)\\'"
    :defines
    markdown-asymmetric-header
    markdown-enable-math
    :config
    (setq markdown-asymmetric-header t)
    (setq markdown-enable-math t))
#+END_SRC

** Org

Enabling ~visual-line-mode~ wraps lines on the nearest space. While this makes prose easier to read, it will make large tables rather unreadable. You can toggle this mode by running ~visual-line-mode~ interactively.

Setting ~org-log-done~ to ~'time~ places the time and date under completed TODO items.

#+BEGIN_SRC emacs-lisp
  (use-package org
    :hook
    (org-mode . visual-line-mode)
    :custom
    (org-log-done 'time))
#+END_SRC

*** Adding additional language support to Org Babel

Org Babel only enables support for Emacs Lisp by default. We can enable other languages by adding them to the list in the following command.

#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages 'org-babel-load-languages
			       '((C . t)
				 (emacs-lisp . t)
				 (scheme . t)))
#+END_SRC

*** Customizing LaTeX source code output

Org Babel tends to use the LaTeX package, [[https://ctan.org/pkg/listings?lang=en][listings]], to generate source code blocks. I think the [[https://ctan.org/pkg/minted?lang=en][minted]] package produces much prettier output, so we can force Org Babel to use it instead.

#+BEGIN_SRC emacs-lisp
  (require 'ox-latex)
  (add-to-list 'org-latex-packages-alist '("" "minted"))
  (setq-default org-latex-listings 'minted)
#+END_SRC

In order for /minted/ to work, [[https://pygments.org/][pygments]] must be installed. Adding the ~-shell-escape~ flag to our invokation of ~pdflatex~ allows the process to access the ~pygmentize~ binary on the system.

#+BEGIN_SRC emacs-lisp
  (setq-default org-latex-pdf-process
	'("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
	  "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+END_SRC

Here, we can tell /minted/ to break long lines instead of having them run off the page.

#+BEGIN_SRC emacs-lisp
  (setq-default org-latex-minted-options '(("breaklines" "true")
					   ("breakanywhere" "true")))
#+END_SRC

*** Wrapping text in LaTeX tables

When exporting an Org document to a PDF using LaTeX, tables with particularly long lines of text may extend off the page. The [[https://texdoc.org/serve/tabularx/0][tabularx]] package implements a version of the tabular environment where the widths of some columns are calculated so that the table fits within a given width.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-latex-packages-alist '("" "tabularx"))
#+END_SRC

This package provides a new ~tabularx~ environment as well as a new alignment specifier, ~X~, which states that the column's width should be determined dynamically.

We can make an Org table use this environment by supplying the ~:environment tabularx~ option in an ~#+ATTR_LATEX~ directive above the table. We can set the width of the table to the width of the text block using the ~:width \textwidth~ option in that same directive, and set all columns to be dynamically sized using the ~:align XXX~ option. You'll have to replace the ~X~'s in this option with a number of ~X~'s equal to the number of columns in your table.

** Python

#+BEGIN_SRC emacs-lisp
  (use-package python
    :mode "\\.py\\'")
#+END_SRC

** Rust

#+BEGIN_SRC emacs-lisp
  (use-package rust-mode
    :mode "\\.rs\\'")
#+END_SRC

** Scheme

[[https://www.nongnu.org/geiser/index.html][Geiser]] is a collection of major and minor modes for Scheme hacking with support for several implementations. I've included the REPLs for [[https://racket-lang.org/][Racket]] and [[https://www.gnu.org/software/guile/][GNU Guile]].

#+BEGIN_SRC emacs-lisp
  (use-package geiser)
  (use-package geiser-racket)
  (use-package geiser-guile)
#+END_SRC
